version: "1.0"

services:
  shopping-list:
    build:
      context: .
      target: development
    volumes:
      - ./src:/shopping-list/src
    ports:
      - $PORT:$PORT
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/shopping-list
    links:
      - mongo
  mongo:
    image: mongo:4.2.0
    ports:
      - 27017:27017
